stages:
  fetch:
    cmd: uv run python src/data/fetch_spin_data.py
    deps:
      - src/data/fetch_spin_data.py
    params:
      - fetch.url
    always_changed: true
    outs:
      - data/raw/lokacija.json

  preprocess:
    cmd: uv run python src/data/process_spin_data.py
    deps:
      - src/data/process_spin_data.py
      - data/raw/lokacija.json
    params:
      - preprocess.station
    outs:
      - data/preprocessed/nesrece_v_cestnem_prometu.csv

  fetch_vreme:
    cmd: uv run python src/data/obcina_vreme.py
    deps:
      - src/data/obcina_vreme.py
    params:
      - fetch_vreme.days_back
      - fetch_vreme.request_sleep
      - fetch_vreme.obcine_path
      - fetch_vreme.url
    always_changed: true
    outs:
      - data/raw/obcina_vreme.csv

  preprocess_vreme:
    cmd: uv run python src/data/process_obcina_vreme.py
    deps:
      - src/data/process_obcina_vreme.py
      - data/raw/obcina_vreme.csv
    params:
      - preprocess_vreme.raw_path
      - preprocess_vreme.processed_path
    outs:
      - data/preprocessed/obcina_vreme_processed.csv

  validate_nesrece:
    cmd: |
      cd gx && uv run python run_checkpoint.py
    deps:
      - data/preprocessed/nesrece_v_cestnem_prometu.csv
      - gx/run_checkpoint.py
      - gx/checkpoints/nesrece_checkpoint.yml
      - gx/expectations/nesrece_suite.json

  validate_vreme:
    cmd: |
      cd gx && uv run python run_checkpoint_vreme.py
    deps:
      - data/preprocessed/obcina_vreme_processed.csv
      - gx/run_checkpoint_vreme.py
      - gx/checkpoints/vreme_checkpoint.yml
      - gx/expectations/vreme_suite.json

  test_nesrece_data:
  cmd: |
    uv run python src/data/test_nesrece_data.py
  deps:
    - data/preprocessed/nesrece_v_cestnem_prometu.csv
    - src/data/test_nesrece_data.py
  outs:
    - data/reference/nesrece_v_cestnem_prometu.csv:
        persist: true
    - reports/nesrece_data_testing_report.html:
        persist: true
  
  train_nesrece:
  cmd: |
    uv run python src/models/train.py
    git commit -am "Updated nesrece model on $(date)" || true
    git push || true
    dvc push || true
  deps:
    - src/models/train.py
    - src/models/preprocess.py
    - data/preprocessed/nesrece_v_cestnem_prometu.csv
    - data/preprocessed/obcina_vreme_processed.csv
    - data/reference/nesrece_v_cestnem_prometu.csv  # output of test_nesrece_data
  params:
    - train_nesrece.nesrece_path
    - train_nesrece.vreme_path
    - train_nesrece.test_size
    - train_nesrece.window_size
    - train_nesrece.random_state
  outs:
    - models/model_nesrece.keras:
        persist: true
    - models/pipeline_nesrece.pkl:
        persist: true
    - models/merger_nesrece.pkl:
        persist: true