stages:
  fetch:
    cmd: uv run python src/data/fetch_spin_data.py
    deps:
      - src/data/fetch_spin_data.py
    params:
      - fetch.url
    always_changed: true
    outs:
      - data/raw/lokacija.json

  preprocess:
    cmd: uv run python src/data/process_spin_data.py
    deps:
      - src/data/process_spin_data.py
      - data/raw/lokacija.json
    params:
      - preprocess.station
    outs:
      - data/preprocessed/nesrece_v_cestnem_prometu.csv

  fetch_vreme:
    cmd: uv run python src/data/obcina_vreme.py
    deps:
      - src/data/obcina_vreme.py
    params:
      - fetch_vreme.days_back
      - fetch_vreme.request_sleep
      - fetch_vreme.obcine_path
      - fetch_vreme.url
    always_changed: true
    outs:
      - data/raw/obcina_vreme.csv

  preprocess_vreme:
    cmd: uv run python src/data/process_obcina_vreme.py
    deps:
      - src/data/process_obcina_vreme.py
      - data/raw/obcina_vreme.csv
    params:
      - preprocess_vreme.raw_path
      - preprocess_vreme.processed_path
    outs:
      - data/preprocessed/obcina_vreme_processed.csv

  validate_nesrece:
    cmd: |
      cd gx && uv run python run_checkpoint.py
    deps:
      - data/preprocessed/nesrece_v_cestnem_prometu.csv
      - gx/run_checkpoint.py
      - gx/checkpoints/nesrece_checkpoint.yml
      - gx/expectations/nesrece_suite.json

  validate_vreme:
    cmd: |
      cd gx && uv run python run_checkpoint_vreme.py
    deps:
      - data/preprocessed/obcina_vreme_processed.csv
      - gx/run_checkpoint_vreme.py
      - gx/checkpoints/vreme_checkpoint.yml
      - gx/expectations/vreme_suite.json