# params.yaml
fetch:
  url: "https://spin3.sos112.si/javno/assets/data/lokacija.json"


fetch_vreme:
  days_back: 2
  request_sleep: 0.2
  obcine_path: "data/raw/obcine.json"
  url: "https://archive-api.open-meteo.com/v1/archive"

preprocess:
  station: "all"

preprocess_vreme:
  raw_path: "data/raw/obcina_vreme.csv"
  processed_path: "data/preprocessed/obcina_vreme_processed.csv"

train_nesrece:
  nesrece_path: data/preprocessed/nesrece_v_cestnem_prometu.csv
  vreme_path:   data/preprocessed/obcina_vreme_processed.csv
  test_size:    2000
  window_size:  24
  random_state: 42
  threshold:    0.3